openapi: 3.1.0
info:
  title: 'Webhook Example'
  version: 1.0.0
components:
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
      type: object
webhooks:
  newPet:
    post:
      operationId: 072580cbd56e3fef2b4c81536d3fd1c6
      requestBody:
        description: 'Information about a new pet in the system'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: 'Return a 200 status to indicate that the data was received successfully'
