sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  include:
    - php: 7.4
      env: CS=yes

before_script:
  - if [[ $TRAVIS_PHP_VERSION > 7.4 ]] ; then sed -i '/friendsofphp\/php-cs-fixer/d' composer.json; fi;
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - ./bin/phpunit
  - if [ $CS = 'yes' ]; then composer run-script lint; fi
