language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  global:
    - PHPUNIT=1

matrix:
  fast_finish: true

  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - sh -c "if [ 'PHPUNIT' = '1' ]; then phpunit; fi"

notifications:
  email: false
